### ISSUE TITLE
Repeated param transform?

### ISSUE THREAD

**Issue by dyth** [deepmind/discretisation_drift#1]
Hello.  Why is [L164-L169](https://github.com/deepmind/dd_two_player_games/blob/275c3b2ed3620e287fbdc507461d9bb6396dd0fb/dd_two_player_games/gan.py#L164-L169) of `gan.py` repeated in [L171-L176](https://github.com/deepmind/dd_two_player_games/blob/275c3b2ed3620e287fbdc507461d9bb6396dd0fb/dd_two_player_games/gan.py#L171-L176)?

**Comment by mihaelacr-google** [comment]
Thanks! This was simply a copy-paste error that did not affect the JAX compilation graph. I removed it now.
